sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678

  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tSVp3rcyCbNMAUMvxxE
    access-key-secret: t14jEEAMaC2O5cOFbCEWroCUSx9KRJ
    bucket-name: sky-takeaway-app-steve

  redis:
    host: localhost
    port: 6379
    password: 123456
